# Generated by Django 5.1.2 on 2025-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='reponse_choisie_qcm',
            field=models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], help_text="Réponse choisie pour affirmation QCM (1-4/null pour 'Je ne sais pas').", null=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse_vf',
            field=models.BooleanField(blank=True, help_text="Réponse pour affirmation Vrai/Faux (True/False/null pour 'Je ne sais pas').", null=True),
        ),
    ]
