# Generated by Django 5.1.2 on 2025-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_affirmation_encadrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Indique si l'activité est lancée et visible par les étudiants."),
        ),
    ]
