# Generated by Django 5.1.2 on 2025-07-20 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_activite_code_activite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='type_apprenant',
        ),
        migrations.AlterField(
            model_name='activite',
            name='code_activite',
            field=models.CharField(help_text='Code unique (1-9 caractères, A-Z, 0-9).', max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_code_activite', message='Le code activité doit contenir entre 1 et 9 caractères alphanumériques majuscules.', regex='^[A-Z0-9]{1,9}$')]),
        ),
    ]
