# Generated by Django 5.1.2 on 2025-04-23 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reponse_reponse_choisie_qcm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affirmation',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='affirmation',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='affirmation',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='affirmation',
            name='option_4',
        ),
        migrations.AddField(
            model_name='activite',
            name='type_affirmation_requise',
            field=models.IntegerField(choices=[(2, 'Vrai/Faux'), (4, '4 Choix Fixes (Toujours/Parfois Vrai/Faux)')], default=2, help_text='Définit le format des affirmations pour cette activité.'),
        ),
        migrations.AddField(
            model_name='affirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activite',
            name='affirmations_associes',
            field=models.ManyToManyField(blank=True, help_text='Affirmations présentées dans cette activité.', related_name='activites', to='api.affirmation'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='code_activite',
            field=models.CharField(help_text='Code unique (1-5 caractères, A-Z, 0-9).', max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_code_activite', message='Le code activité doit contenir entre 1 et 5 caractères alphanumériques majuscules.', regex='^[A-Z0-9]{1,5}$')]),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='affirmation',
            field=models.TextField(help_text="Le texte principal de l'affirmation."),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='explication',
            field=models.TextField(blank=True, help_text='Explication (pourquoi vraie/fausse).', null=True),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='is_correct_vf',
            field=models.BooleanField(blank=True, help_text='Est-ce vrai? (pour nbr_reponses=2)', null=True),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='nbr_reponses',
            field=models.IntegerField(choices=[(2, 'Vrai/Faux'), (4, '4 Choix Fixes (Toujours/Parfois Vrai/Faux)')], help_text='Format défini lors de la création pour une activité (2 ou 4).'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='reponse_correcte_qcm',
            field=models.IntegerField(blank=True, choices=[(1, 'Choix 1'), (2, 'Choix 2'), (3, 'Choix 3'), (4, 'Choix 4')], help_text='Index (1-4) du choix fixe correct (pour nbr_reponses=4).', null=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse_choisie_qcm',
            field=models.IntegerField(blank=True, choices=[(1, 'Choix 1'), (2, 'Choix 2'), (3, 'Choix 3'), (4, 'Choix 4')], help_text='Réponse QCM (1-4).', null=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse_vf',
            field=models.BooleanField(blank=True, help_text='Réponse V/F.', null=True),
        ),
    ]
