# Generated by Django 5.1.2 on 2025-05-08 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_affirmation_option_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmation',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affirmations_creees', to=settings.AUTH_USER_MODEL),
        ),
    ]
