# Generated by Django 5.1.2 on 2025-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_activite_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='type_apprenant',
            field=models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], default='interne', help_text="Type d'apprenant ciblé par l'activité.", max_length=10),
        ),
    ]
