# Generated by Django 5.1.2 on 2025-07-20 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activite_type_apprenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='code_activite',
            field=models.CharField(help_text='Code unique (1-8 caractères, A-Z, 0-9).', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_code_activite', message='Le code activité doit contenir entre 1 et 8 caractères alphanumériques majuscules.', regex='^[A-Z0-9]{1,8}$')]),
        ),
    ]
