# Generated by Django 5.1.2 on 2025-07-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_activite_type_apprenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmation',
            name='is_correct_vf',
            field=models.BooleanField(blank=True, help_text="OPTIONNEL: Valeur de vérité (si l'encadrant souhaite l'indiquer)", null=True),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='reponse_correcte_qcm',
            field=models.IntegerField(blank=True, choices=[(1, 'Choix 1'), (2, 'Choix 2'), (3, 'Choix 3'), (4, 'Choix 4')], help_text="OPTIONNEL: Index (1-4) du choix correct (si l'encadrant souhaite l'indiquer)", null=True),
        ),
    ]
