# Generated by Django 5.1.2 on 2024-12-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_activite_etudiants_alter_affirmation_explication_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reponse",
            unique_together={("activite_affirmation", "etudiant")},
        ),
    ]
